In [146]:
import pandas as pd
pd.set_option('display.max_colwidth',100)

In [147]:
Data=pd.read_excel('drive/My Drive/Ankit/october2020 codalab/english/Constraint_English_Train.xlsx')
Data.dropna(inplace = True)
Data.head()

id  ... label
0   1  ...  real
1   2  ...  real
2   3  ...  fake
3   4  ...  real
4   5  ...  real

[5 rows x 3 columns]

In [148]:
#Data.columns=['id','Post','label']

In [149]:
!pip install neattext

In [150]:
import neattext as nt
import neattext.functions as nfx

In [151]:
# Explore For Noise
Data['tweet'].apply(lambda x:nt.TextFrame(x).noise_scan())

0        {'text_noise': 6.315789473684211, 'text_length': 190, 'noise_count': 12}
1       {'text_noise': 10.077519379844961, 'text_length': 129, 'noise_count': 13}
2        {'text_noise': 8.396946564885496, 'text_length': 131, 'noise_count': 11}
3        {'text_noise': 9.313725490196079, 'text_length': 204, 'noise_count': 19}
4        {'text_noise': 9.090909090909092, 'text_length': 231, 'noise_count': 21}
                                          ...                                    
6415      {'text_noise': 10.126582278481013, 'text_length': 79, 'noise_count': 8}
6416    {'text_noise': 18.947368421052634, 'text_length': 190, 'noise_count': 36}
6417                  {'text_noise': 10.0, 'text_length': 100, 'noise_count': 10}
6418       {'text_noise': 4.081632653061225, 'text_length': 49, 'noise_count': 2}
6419     {'text_noise': 9.859154929577464, 'text_length': 213, 'noise_count': 21}
Name: tweet, Length: 6420, dtype: object

In [152]:
# Explore For Noise
Data['tweet'].apply(lambda x:nt.TextExtractor(x).extract_stopwords())

0                                            [the, in, the, in, between, are, and, the, at]
1                                                                [a, from, last, of, those]
2                                                                             [as, not, to]
3                                             [we, have, in, and, as, on, have, been, done]
4                          [can, but, if, you, at, the, per, are, more, per, than, or, and]
                                               ...                                         
6415                                                      [a, for, please, from, your, and]
6416                      [that, a, not, to, be, with, and, the, whole, has, been, in, the]
6417                                                     [a, has, already, been, and, will]
6418                                                                                   [in]
6419    [it, has, been, since, the, last, of, was, from, an, the, of, of, in, an

In [153]:
dir(nfx)   #neat text function can be use to remove or extract something so easily

['CURRENCY_REGEX',
 'CURRENCY_SYMB_REGEX',
 'Counter',
 'DATE_REGEX',
 'EMAIL_REGEX',
 'EMOJI_REGEX',
 'HASTAG_REGEX',
 'MOST_COMMON_PUNCT_REGEX',
 'NUMBERS_REGEX',
 'PHONE_REGEX',
 'SPECIAL_CHARACTERS_REGEX',
 'STOPWORDS',
 'STOPWORDS_de',
 'STOPWORDS_en',
 'STOPWORDS_es',
 'STOPWORDS_fr',
 'STOPWORDS_ru',
 'STOPWORDS_yo',
 'TextFrame',
 'URL_PATTERN',
 'USER_HANDLES_REGEX',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__generate_text',
 '__loader__',
 '__name__',
 '__numbers_dict',
 '__package__',
 '__spec__',
 '_lex_richness_herdan',
 '_lex_richness_maas_ttr',
 'clean_text',
 'defaultdict',
 'digit2words',
 'extract_currencies',
 'extract_currency_symbols',
 'extract_dates',
 'extract_emails',
 'extract_emojis',
 'extract_hashtags',
 'extract_html_tags',
 'extract_numbers',
 'extract_pattern',
 'extract_phone_numbers',
 'extract_special_characters',
 'extract_stopwords',
 'extract_urls',
 'extract_userhandles',
 'fix_contractions',
 'generate_sentence',
 'hamming_dista

In [154]:
# Explore For Noise
Data['tweet']=Data['tweet'].apply(nfx.remove_stopwords)

Data['tweet']=Data['tweet'].apply(nfx.remove_emojis)
Data['tweet']=Data['tweet'].apply(nfx.remove_html_tags)

Data['tweet']=Data['tweet'].apply(nfx.remove_numbers)
Data['tweet']=Data['tweet'].apply(nfx.remove_punctuations)
Data['tweet']=Data['tweet'].apply(nfx.remove_multiple_spaces)

Data['tweet']=Data['tweet'].apply(nfx.remove_special_characters)
Data['tweet']=Data['tweet'].apply(nfx.remove_bad_quotes)

In [155]:
Data['tweet']

0       CDC currently reports deaths general discrepancies death counts different sources small explicab...
1               States reported deaths small rise Tuesday Southern states reported deaths httpstcoYASGRTTux
2       Politically Correct Woman Almost Uses Pandemic Excuse Reuse Plastic Bag httpstcothFGuNFPe corona...
3       IndiaFightsCorona COVID testing laboratories India th August tests  ProfBhargava DG ICMRDELHI St...
4       Populous states generate large case counts look new cases million today smaller states showing c...
                                                       ...                                                 
6415                                                       tiger tested positive COVID stay away pets birds
6416    Autopsies prove COVID is blood clot pneumonia and ought fought antibiotics world wrong treating ...
6417                                     A post claims COVID vaccine developed cause widespread infertility
6418                        

In [156]:
import keras
from keras.preprocessing.text import Tokenizer
tok1 = Tokenizer(char_level=False, filters ='!"$%&@()*+,-./:;”“<=>?[\\]^_`{|}~\t\n', lower = True)

In [157]:
tok1.fit_on_texts(Data['tweet'])
words=len(tok1.word_counts)
words

17115

In [158]:
word_list=[tok1.word_index]
word_list

[{'covid': 1,
  'cases': 2,
  'coronavirus': 3,
  'new': 4,
  'people': 5,
  'tests': 6,
  'deaths': 7,
  'states': 8,
  'total': 9,
  'number': 10,
  'confirmed': 11,
  'reported': 12,
  'testing': 13,
  'amp': 14,
  'health': 15,
  'india': 16,
  'today': 17,
  'state': 18,
  'report': 19,
  'indiafightscorona': 20,
  'pandemic': 21,
  'virus': 22,
  'day': 23,
  'case': 24,
  'patients': 25,
  'vaccine': 26,
  'update': 27,
  'says': 28,
  'data': 29,
  'hospital': 30,
  'rt': 31,
  'tested': 32,
  'k': 33,
  'positive': 34,
  'days': 35,
  'test': 36,
  'daily': 37,
  'trump': 38,
  'lockdown': 39,
  'active': 40,
  'spread': 41,
  'rate': 42,
  'video': 43,
  'recovered': 44,
  'world': 45,
  'shows': 46,
  'million': 47,
  'yesterday': 48,
  'news': 49,
  'lagos': 50,
  'president': 51,
  'coronavirusupdates': 52,
  'isolation': 53,
  'death': 54,
  'numbers': 55,
  'government': 56,
  'mohfwindia': 57,
  'risk': 58,
  'said': 59,
  'fct': 60,
  'country': 61,
  'discharged': 62,

In [159]:
encoded=tok1.texts_to_sequences(Data['tweet'])
print(Data['tweet'][0])
encoded[0]

CDC currently reports deaths general discrepancies death counts different sources small explicable death toll stands roughly people today


[64,
 173,
 159,
 7,
 592,
 6511,
 54,
 1004,
 302,
 1465,
 536,
 6512,
 54,
 501,
 407,
 1466,
 5,
 17]

In [160]:
import numpy as np
from keras.utils.np_utils import to_categorical
classes_list = ["real","fake"]
label_index = Data['label'].apply(classes_list.index)
label1 = np.asarray(label_index)
label = to_categorical(np.asarray(label1))
label

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [1., 0.]], dtype=float32)

In [161]:
##         Padding encoded sequence of words
from keras.preprocessing import sequence
max_length=25
padd = sequence.pad_sequences(encoded, maxlen=max_length, padding='post')
padd

array([[  64,  173,  159, ...,    0,    0,    0],
       [   8,   12,    7, ...,    0,    0,    0],
       [4563, 1603,  303, ...,    0,    0,    0],
       ...,
       [ 181,  196,   76, ...,    0,    0,    0],
       [2603,  831, 2483, ...,    0,    0,    0],
       [  35,   24,    1, ...,    0,    0,    0]], dtype=int32)

#CNN

In [162]:
# importing libraries for creating model
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten, Embedding,MaxPool1D
from keras.layers import Conv1D, GlobalMaxPooling1D, MaxPooling1D

In [189]:
model = Sequential()
model.add(Embedding(input_dim = words + 1, output_dim = 100,input_length=max_length))
model.add(Conv1D(filters =32,kernel_size=2, activation='relu'))
model.add(MaxPooling1D(3))
model.add(Flatten())
model.add(Dense(32, activation = 'relu'))
#model.add(Dense(16, activation = 'relu'))
model.add(Dense(2, activation = 'sigmoid'))
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_5 (Embedding)      (None, 25, 100)           1711600   
_________________________________________________________________
conv1d_5 (Conv1D)            (None, 24, 32)            6432      
_________________________________________________________________
max_pooling1d_5 (MaxPooling1 (None, 8, 32)             0         
_________________________________________________________________
flatten_5 (Flatten)          (None, 256)               0         
_________________________________________________________________
dense_11 (Dense)             (None, 32)                8224      
_________________________________________________________________
dense_12 (Dense)             (None, 2)                 66        
Total params: 1,726,322
Trainable params: 1,726,322
Non-trainable params: 0
____________________________________________

In [190]:
## compile

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])

In [191]:
model.fit(padd,label,epochs=20,verbose=1,batch_size=32)

Epoch 1/20
201/201 [==============================] - 4s 21ms/step - loss: 0.3795 - acc: 0.8341
Epoch 2/20
201/201 [==============================] - 4s 21ms/step - loss: 0.0761 - acc: 0.9740
Epoch 3/20
201/201 [==============================] - 4s 20ms/step - loss: 0.0110 - acc: 0.9977
Epoch 4/20
201/201 [==============================] - 4s 21ms/step - loss: 0.0022 - acc: 0.9994
Epoch 5/20
201/201 [==============================] - 4s 21ms/step - loss: 7.6053e-04 - acc: 1.0000
Epoch 6/20
201/201 [==============================] - 4s 21ms/step - loss: 3.6406e-04 - acc: 1.0000
Epoch 7/20
201/201 [==============================] - 4s 21ms/step - loss: 2.2815e-04 - acc: 1.0000
Epoch 8/20
201/201 [==============================] - 4s 21ms/step - loss: 1.5914e-04 - acc: 1.0000
Epoch 9/20
201/201 [==============================] - 4s 21ms/step - loss: 1.1731e-04 - acc: 1.0000
Epoch 10/20
201/201 [==============================] - 4s 21ms/step - loss: 8.8678e-05 - acc: 1.0000
Epoch 11/20
201

In [192]:
#model.fit(padd,label,epochs=20,verbose=1)

In [193]:
# model testing
#predictions_test = model.predict(x_test)
# Finding out of two output neurons which one has highest probability
# It will return us the predicted class
# It will convert probability into final class 1 and 0

#predictions_test1 = np.zeros_like(predictions_test)
#predictions_test1[np.arange(len(predictions_test)), predictions_test.argmax(1)] = 1

#print(predictions_test)
#print(predictions_test1)

In [194]:
#Accuracy of the model
from sklearn.metrics import classification_report
#print(classification_report(y_test,predictions_test1))

#validation

In [195]:
vData =pd.read_excel('drive/My Drive/Ankit/october2020 codalab/english/Constraint_English_Val.xlsx')
vData.dropna(inplace = True)
vData.head()

id  ... label
0   1  ...  fake
1   2  ...  fake
2   3  ...  fake
3   4  ...  fake
4   5  ...  real

[5 rows x 3 columns]

In [196]:
## doing preprocessing as above

vData['tweet']=vData['tweet'].apply(nfx.remove_stopwords)

vData['tweet']=vData['tweet'].apply(nfx.remove_emojis)
vData['tweet']=vData['tweet'].apply(nfx.remove_html_tags)

vData['tweet']=vData['tweet'].apply(nfx.remove_numbers)
vData['tweet']=vData['tweet'].apply(nfx.remove_punctuations)
vData['tweet']=vData['tweet'].apply(nfx.remove_multiple_spaces)

vData['tweet']=vData['tweet'].apply(nfx.remove_special_characters)
vData['tweet']=vData['tweet'].apply(nfx.remove_bad_quotes)

In [197]:
encoded1=tok1.texts_to_sequences(vData['tweet'])
print(vData['tweet'][0])
encoded1[0]

Chinese converting Islam realising muslim affected Coronavirus COVD country


[193, 10593, 4126, 749, 410, 3, 10181, 61]

In [198]:
test_label_index = vData['label'].apply(classes_list.index)
test_label1 = np.asarray(test_label_index)
test_label = to_categorical(np.asarray(test_label1))
test_label[7:]

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [1., 0.]], dtype=float32)

In [199]:
padded = sequence.pad_sequences(encoded1, maxlen=max_length, padding='post')
padded[0]

array([  193, 10593,  4126,   749,   410,     3, 10181,    61,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0], dtype=int32)

In [200]:
# validation

test_predictions = model.predict(padded)
# Finding out of two output neurons which one has highest probability
# It will return us the predicted class
# It will convert probability into final class 1 and 0
test_predictions1 = np.zeros_like(test_predictions)
test_predictions1[np.arange(len(test_predictions)), test_predictions.argmax(1)] = 1
#print(test_predictions)
#print(test_predictions1)

In [201]:
#Accuracy 
from sklearn.metrics import classification_report
print(classification_report(test_label,test_predictions1))

              precision    recall  f1-score   support

           0       0.95      0.91      0.93      1120
           1       0.91      0.95      0.93      1020

   micro avg       0.93      0.93      0.93      2140
   macro avg       0.93      0.93      0.93      2140
weighted avg       0.93      0.93      0.93      2140
 samples avg       0.93      0.93      0.93      2140

